import type { Lang } from '../types';

export const PORTONE_STORE_ID = "store-96a3d482-0e51-4723-9ab8-59a55fb52159";
export const CHANNEL_KEY_KAKAOPAY = "channel-key-e2b91f60-183c-4b53-a783-752cf3bfbb8c";
export const CHANNEL_KEY_EXIMBAY = "channel-key-8d2ca50f-f661-4d7b-9ae1-e2d0ceda6c6a";

export const MAX_TEXT_LENGTH = 2500;

export const HIRAGANA_GRID: string[][] = [
  ['あ', 'い', 'う', 'え', 'お'],
  ['か', 'き', 'く', 'け', 'こ'],
  ['さ', 'し', 'す', 'せ', 'そ'],
  ['た', 'ち', 'つ', 'て', 'と'],
  ['な', 'に', 'ぬ', 'ね', 'の'],
  ['は', 'ひ', 'ふ', 'へ', 'ほ'],
  ['ま', 'み', 'む', 'め', 'も'],
  ['や', 'ゆ', 'よ'],
  ['ら', 'り', 'る', 'れ', 'ろ'],
  ['わ', 'を', 'ん']
];

export const KATAKANA_GRID: string[][] = [
  ['ア', 'イ', 'ウ', 'エ', 'オ'],
  ['カ', 'キ', 'ク', 'ケ', 'コ'],
  ['サ', 'シ', 'ス', 'セ', 'ソ'],
  ['タ', 'チ', 'ツ', 'テ', 'ト'],
  ['ナ', 'ニ', 'ヌ', 'ネ', 'ノ'],
  ['ハ', 'ヒ', 'フ', 'ヘ', 'ホ'],
  ['マ', 'ミ', 'ム', 'メ', 'モ'],
  ['ヤ', 'ユ', 'ヨ'],
  ['ラ', 'リ', 'ル', 'レ', 'ロ'],
  ['ワ', 'ヲ', 'ン']
];

export const DICT: Record<Lang, Record<string, string>> = {
  ko: {
    analyzeTab: "문장 분석",
    decksTab: "단어장 관리",
    quizTab: "퀴즈 풀기",
    streak: "일 연속",
    membership: "프리미엄",
    login: "로그인",
    logout: "로그아웃",
    loginSignup: "로그인 / 회원가입",
    deckSidebarTitle: "단어장",
    deckLabel: "암기장:",
    newDeck: "+ 새 암기장",
    searchPlaceholder: "🔍 단어/뜻 검색...",
    inputTitle: "일본어 문장 입력 또는 이미지 첨부",
    inputPlaceholder: "분석할 일본어 문장이나 기사를 입력하거나, 이미지를 드래그 앤 드롭 / Ctrl+V로 붙여넣으세요.",
    selectImage: "🖼️ 이미지 파일 선택",
    dragNotice: "Ctrl+V 또는 파일 드래그도 가능",
    analyzeBtn: "분석하기",
    analyzing: "분석 중...",
    cooldown: "잠시 대기...",
    noteTitle: "본문 노트",
    stopAudio: "중단",
    fontSerif: "명조체",
    fontSans: "고딕체",
    wordCardTitle: "주요 단어 카드",
    kanjiCardTitle: "핵심 한자 정보",
    grammarCardTitle: "문법 구조 및 활용",
    targetDeck: "저장할 암기장:",
    addWordBtn: "+ 단어장에 저장",
    hideMeaning: "🙈 뜻 가리기 모드",
    showMeaning: "🙈 뜻 가림막 해제",
    partOfSpeech: "품사",
    meaning: "뜻",
    delete: "삭제",
    exportAnki: "⚡ Anki 카드 내보내기",
    makePdf: "📝 시험지 만들기 (PDF)",
    premiumTitle: "YomiYomi 프리미엄",
    premiumDesc: "무제한 문장 분석, AI 단어장 동기화 및 퀴즈 기능을 이용해 보세요.",
    plan3m: "3개월 플랜",
    plan1y: "1년 구독",
    planLifetime: "평생 이용권",
    off20: "20% 할인",
    bestTag: "🔥 BEST",
    price3m: "$12.00",
    price1y: "$38.40",
    priceLifetime: "$45.00",
    perMonth3: "$4.00 / 월",
    perMonth12: "$3.20 / 월",
    unlimitedText: "무제한",
    selectPlan: "선택하기",
    subscribePlan: "구독하기",
    payTitlePre: "[",
    payTitlePost: " 플랜] 결제 수단을 선택해 주세요",
    payAmountLabel: "결제 금액: ",
    reselectPlan: "◀ 플랜 다시 선택하기",
    close: "✕",
    modeFurigana: "후리가나",
    modeYomigana: "요미가나",
    modeOff: "OFF",
    gojuonChart: "오십음도 표",
    hiragana: "히라가나",
    katakana: "카타카나",
    recSitesTitle: "추천 학습 사이트",
    noSavedWords: "저장된 단어가 없습니다.",
    noSearchWords: "검색어와 일치하는 단어가 없습니다.",
    savedWordsLabel: "저장된 단어: ",
    unitCount: "개",
    charCount: "자",
    unitTimes: "회",
    confirmBtn: "확인",
    cancelBtn: "취소",
    wordCardListTitle: "단어 카드 리스트",
    allDeckTitle: "전체 단어장 목록",
    quizTitle: "단어 암기 3지선다 퀴즈",
    quizSelectDesc: "퀴즈를 출제할 단어장을 선택해 주세요.",
    quizStartBtn: "선택한 단어장으로 퀴즈 시작하기",
    quizCompleteTitle: "퀴즈 완료!",
    quizScoreText: "맞히셨습니다.",
    quizBackBtn: "단어장 선택으로 돌아가기",
    quizSurrenderBtn: "🏳️ 퀴즈 포기하기",
    quizMinCardsAlert: "퀴즈를 진행하려면 최소 3개 이상의 단어가 저장되어 있어야 합니다.",
    quizSurrenderConfirm: "퀴즈를 중단하고 단어장 선택 화면으로 돌아가시겠습니까?",
    logoutConfirm: "로그아웃 하시겠습니까?",
    deckDeleteModalTitle: "암기장 삭제 확인",
    deckDeleteModalDesc: "암기장을 삭제하시겠습니까?\n확인을 위해 아래 입력창에 암기장 이름을 똑같이 적어주세요.",
    newDeckModalTitle: "새 암기장 만들기",
    newDeckModalPlaceholder: "암기장 이름을 입력하세요",
    createBtn: "생성하기",
    duplicateWordMsg: "이미 들어있는 단어입니다.",
    alertNoDeck: "최소 하나의 암기장은 유지되어야 합니다.",
    settingsTitle: "계정 및 서비스 설정",
    changeNickname: "닉네임 변경",
    changeLanguage: "서비스 언어 설정",
    saveProfileBtn: "프로필 정보 저장하기",
    premiumMembership: "프리미엄 구독",
    freePlanUsing: "무료 플랜 이용 중",
    usingPlan: " 이용 중",
    changePlan: "플랜 변경",
    cancelSubscription: "구독 해지 예약",
    cancelSubConfirm: "다음 결제 주기 해지를 예약하시겠습니까?\n만료일까지는 모든 프리미엄 혜택을 계속 이용하실 수 있습니다.",
    subCancelledMsg: "구독 해지가 예약되었습니다. 만료일까지 프리미엄 혜택이 유지됩니다.",
    scheduledCancelLabel: "해지 예약됨",
    nextPayDateLabel: "다음 결제 예정일: ",
    expDateLabel: "이용 만료 예정일: ",
    daysLeftLabel: "일 남음",
    deleteAccountBtn: "⚠️ 계정 탈퇴하기",
    deleteAccountConfirm: "정말로 계정을 탈퇴하시겠습니까?\n\n⚠️ 주의: 탈퇴 시 자동 결제가 해지되며, 남은 프리미엄 이용 기간 및 저장된 모든 단어장 데이터가 즉시 말소되어 복구할 수 없습니다.",
    deleteAccountSuccess: "계정이 정상적으로 탈퇴되었습니다. 이용해 주셔서 감사합니다.",
    loginSub: "서비스 이용을 위해 로그인해 주세요",
    signupSub: "새 계정을 만듭니다",
    signup: "회원가입",
    nicknameLabel: "이름 (닉네임)",
    emailLabel: "이메일 주소",
    passwordLabel: "비밀번호",
    confirmPasswordLabel: "비밀번호 확인",
    passwordCheckPrompt: "Please check password requirements.",
    passwordMismatch: "Passwords do not match.",
    emailVerificationAlert: "Email not verified. Please click the verification link sent to your inbox before logging in.",
    emailAlreadyInUse: "This email address is already registered.",
    loginBtn: "로그인하기",
    signupBtn: "가입하기",
    or: "또는",
    googleLogin: "구글로 계속하기",
    pricingSubNotice: "* 가입 후 언제든지 설정을 통해 구독 상태를 관리하거나 해지할 수 있습니다.",
    promptNewDeckName: "새 암기장 이름을 입력하세요:",
    deckNameMismatch: "암기장 이름이 일치하지 않습니다.",
    loginRequired: "로그인이 필요한 서비스입니다.",
    subscribeConfirmPre: " 플랜을 구독하시겠습니까?",
    subscribeSuccessPost: " 프리미엄 구독이 완료되었습니다!",
    imageOnlyAlert: "이미지 파일만 업로드할 수 있습니다.",
    loginSuccess: "로그인되었습니다!",
    signupSuccess: "Sign up complete! Verification email sent. Please verify your email before logging in.",
    profileUpdateSuccess: "프로필 정보가 수정되었습니다!",
    dailyLimitBadge: "오늘 남은 무료 분석: ",
    dailyLimitReached: "오늘의 무료 분석 횟수(3회)를 모두 사용하셨습니다. 프리미엄으로 무제한 이용해 보세요!",
    loginGateMsg: "문장 분석 기능은 로그인 후 이용하실 수 있습니다.",
    quizLockedTitle: "🔒 퀴즈 풀기는 프리미엄 전용 기능입니다",
    quizLockedDesc: "프리미엄에 가입하시고 무제한 단어 퀴즈와 문장 분석 혜택을 누려보세요!",
    pdfLockedMsg: "PDF 시험지 생성 기능은 프리미엄 전용 서비스입니다."
  },
  en: {
    analyzeTab: "Analyze",
    decksTab: "Vocabulary",
    quizTab: "Quiz",
    streak: "Days Streak",
    membership: "Premium",
    login: "Login",
    logout: "Logout",
    loginSignup: "Login / Sign Up",
    deckSidebarTitle: "Vocabulary",
    deckLabel: "Deck:",
    newDeck: "+ New Deck",
    searchPlaceholder: "🔍 Search word/meaning...",
    inputTitle: "Enter Japanese sentence or attach image",
    inputPlaceholder: "Enter Japanese text or article to analyze, or drag & drop / Ctrl+V an image.",
    selectImage: "🖼️ Select Image File",
    dragNotice: "Ctrl+V or Drag & Drop available",
    analyzeBtn: "Analyze",
    analyzing: "Analyzing...",
    cooldown: "Please wait...",
    noteTitle: "Main Text Note",
    stopAudio: "Stop",
    fontSerif: "Serif",
    fontSans: "Sans-Serif",
    wordCardTitle: "Key Words",
    kanjiCardTitle: "Key Kanji Info",
    grammarCardTitle: "Grammar & Usage",
    targetDeck: "Save to Deck:",
    addWordBtn: "+ Save to Deck",
    hideMeaning: "🙈 Hide Meanings",
    showMeaning: "🙈 Show Meanings",
    partOfSpeech: "POS",
    meaning: "Meaning",
    delete: "Delete",
    exportAnki: "⚡ Export Anki Deck",
    makePdf: "📝 Test Sheet (PDF)",
    premiumTitle: "YomiYomi Premium",
    premiumDesc: "Enjoy unlimited sentence analysis, AI vocabulary sync, and quiz access.",
    plan3m: "3 Months Plan",
    plan1y: "1 Year Plan",
    planLifetime: "Lifetime Pass",
    off20: "20% OFF",
    bestTag: "🔥 BEST",
    price3m: "$12.00",
    price1y: "$38.40",
    priceLifetime: "$45.00",
    perMonth3: "$4.00/mo",
    perMonth12: "$3.20/mo",
    unlimitedText: "Unlimited",
    selectPlan: "Select",
    subscribePlan: "Subscribe",
    payTitlePre: "Select payment method for [",
    payTitlePost: " Plan]",
    payAmountLabel: "Total Amount: ",
    reselectPlan: "◀ Select another plan",
    close: "✕",
    modeFurigana: "Furigana",
    modeYomigana: "Yomigana",
    modeOff: "OFF",
    gojuonChart: "Gojuon Chart",
    hiragana: "Hiragana",
    katakana: "Katakana",
    recSitesTitle: "Recommended Sites",
    noSavedWords: "No saved words.",
    noSearchWords: "No matching words found.",
    savedWordsLabel: "Saved words: ",
    unitCount: " items",
    charCount: " chars",
    unitTimes: " times",
    confirmBtn: "Confirm",
    cancelBtn: "Cancel",
    wordCardListTitle: "Word Card List",
    allDeckTitle: "All Decks",
    quizTitle: "Vocabulary Quiz",
    quizSelectDesc: "Select decks for the quiz.",
    quizStartBtn: "Start Quiz",
    quizCompleteTitle: "Quiz Completed!",
    quizScoreText: "correct answers.",
    quizBackBtn: "Back to Selection",
    quizSurrenderBtn: "🏳️ Give Up",
    quizMinCardsAlert: "At least 3 saved words are required for a quiz.",
    quizSurrenderConfirm: "Are you sure you want to stop the quiz?",
    logoutConfirm: "Are you sure you want to log out?",
    deckDeleteModalTitle: "Delete Deck Confirmation",
    deckDeleteModalDesc: "Delete this deck?\nType the deck name below to confirm.",
    newDeckModalTitle: "Create New Deck",
    newDeckModalPlaceholder: "Enter deck name",
    createBtn: "Create",
    duplicateWordMsg: "This word is already saved in the deck.",
    alertNoDeck: "At least one deck must be maintained.",
    settingsTitle: "Account & Settings",
    changeNickname: "Change Nickname",
    changeLanguage: "Language Preference",
    saveProfileBtn: "Save Profile",
    premiumMembership: "Premium Subscription",
    freePlanUsing: "Using Free Plan",
    usingPlan: " Plan Active",
    changePlan: "Change Plan",
    cancelSubscription: "Cancel Renewal",
    cancelSubConfirm: "Cancel automatic renewal? You will retain Premium access until the end of your billing cycle.",
    subCancelledMsg: "Automatic renewal cancelled. Access remains active until expiration.",
    scheduledCancelLabel: "Cancels Pending",
    nextPayDateLabel: "Next Renewal: ",
    expDateLabel: "Expiration: ",
    daysLeftLabel: " days left",
    deleteAccountBtn: "⚠️ Delete Account",
    deleteAccountConfirm: "Are you sure you want to delete your account?\n\n⚠️ Warning: Your subscription will be cancelled and all remaining Premium days and data will be permanently erased.",
    deleteAccountSuccess: "Your account has been deleted successfully.",
    loginSub: "Please log in to use the service",
    signupSub: "Create a new account",
    signup: "Sign Up",
    nicknameLabel: "Name / Nickname",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    passwordCheckPrompt: "Please check password requirements.",
    passwordMismatch: "Passwords do not match.",
    emailVerificationAlert: "Email not verified. Please click the verification link sent to your inbox before logging in.",
    emailAlreadyInUse: "This email address is already registered.",
    loginBtn: "Log In",
    signupBtn: "Sign Up",
    or: "OR",
    googleLogin: "Continue with Google",
    pricingSubNotice: "* You can manage or cancel your subscription anytime in Settings.",
    promptNewDeckName: "Enter new deck name:",
    deckNameMismatch: "Deck name does not match.",
    loginRequired: "Login is required for this service.",
    subscribeConfirmPre: " plan?",
    subscribeSuccessPost: " Premium Subscription activated!",
    imageOnlyAlert: "Only image files can be uploaded.",
    signupSuccess: "Sign up complete! Verification email sent. Please verify your email before logging in.",
    profileUpdateSuccess: "Profile updated successfully!",
    dailyLimitBadge: "Daily Free Limit Left: ",
    dailyLimitReached: "You've reached your daily limit of 3 free analyses. Upgrade to Premium for unlimited access!",
    loginGateMsg: "Please log in to use the sentence analysis feature.",
    quizLockedTitle: "🔒 Quizzes are Premium Only",
    quizLockedDesc: "Upgrade to Premium to unlock unlimited quizzes and sentence analysis!",
    pdfLockedMsg: "PDF Test Sheet generation is available exclusively for Premium members."
  },
  'zh-CN': {
    analyzeTab: "句子分析",
    decksTab: "单词整理",
    quizTab: "单词测验",
    streak: "天连续",
    membership: "高级版",
    login: "登录",
    logout: "登出",
    loginSignup: "登录 / 注册",
    deckSidebarTitle: "单词整理",
    deckLabel: "卡片盒:",
    newDeck: "+ 新建单词本",
    searchPlaceholder: "🔍 搜索单词/释义...",
    inputTitle: "输入日语句子或附加图片",
    inputPlaceholder: "请输入要分析的日语句子或文章，或拖放/Ctrl+V粘贴图片。",
    selectImage: "🖼️ 选择图片文件",
    dragNotice: "支持 Ctrl+V 或拖放图片",
    analyzeBtn: "开始分析",
    analyzing: "分析中...",
    cooldown: "请稍候...",
    noteTitle: "原文笔记",
    stopAudio: "停止",
    fontSerif: "明朝体",
    fontSans: "黑体",
    wordCardTitle: "核心词汇",
    kanjiCardTitle: "重点汉字",
    grammarCardTitle: "语法结构",
    targetDeck: "保存至单词本:",
    addWordBtn: "+ 保存至单词整理",
    hideMeaning: "🙈 隐藏释义",
    showMeaning: "🙈 显示释义",
    partOfSpeech: "词性",
    meaning: "释义",
    delete: "删除",
    exportAnki: "⚡ 导出 Anki 卡包",
    makePdf: "📝 生成测试卷 (PDF)",
    premiumTitle: "YomiYomi 高级版",
    premiumDesc: "享受无限句子分析、AI 单词整理同步及测验功能。",
    plan3m: "3个月 方案",
    plan1y: "1年 方案",
    planLifetime: "终身卡",
    off20: "20% 优惠",
    bestTag: "🔥 BEST",
    price3m: "$12.00",
    price1y: "$38.40",
    priceLifetime: "$45.00",
    perMonth3: "$4.00/月",
    perMonth12: "$3.20/月",
    unlimitedText: "无限使用",
    selectPlan: "选择",
    subscribePlan: "立即订阅",
    payTitlePre: "请选择 [",
    payTitlePost: " 方案] 的支付方式",
    payAmountLabel: "支付金额：",
    reselectPlan: "◀ 重新选择方案",
    close: "✕",
    modeFurigana: "振假名(上)",
    modeYomigana: "读音(旁)",
    modeOff: "关闭",
    gojuonChart: "五十音图",
    hiragana: "平假名",
    katakana: "片假名",
    recSitesTitle: "推荐学习网站",
    noSavedWords: "暂无保存的单词。",
    noSearchWords: "未找到匹配的单词。",
    savedWordsLabel: "已保存单词: ",
    unitCount: "个",
    charCount: "字",
    unitTimes: "次",
    confirmBtn: "确定",
    cancelBtn: "取消",
    wordCardListTitle: "单词卡片列表",
    allDeckTitle: "全部单词本",
    quizTitle: "单词选择题测验",
    quizSelectDesc: "请选择出题单词本。",
    quizStartBtn: "开始测验",
    quizCompleteTitle: "测验完成！",
    quizScoreText: "答对题目。",
    quizBackBtn: "返回单词本选择",
    quizSurrenderBtn: "🏳️ 放弃测验",
    quizMinCardsAlert: "需要至少 3 个保存的单词才能开始测验。",
    quizSurrenderConfirm: "确定要放弃当前测验吗？",
    logoutConfirm: "确定要退出登录吗？",
    deckDeleteModalTitle: "确认删除单词本",
    deckDeleteModalDesc: "确定删除此单词本吗？\n请在下方输入单词本名称以确认。",
    newDeckModalTitle: "新建单词本",
    newDeckModalPlaceholder: "请输入单词本名称",
    createBtn: "创建",
    duplicateWordMsg: "该单词已存在于单词本中。",
    alertNoDeck: "必须至少保留一个单词本。",
    settingsTitle: "个人信息与设置",
    changeNickname: "修改昵称",
    changeLanguage: "语言偏好",
    saveProfileBtn: "保存个人信息",
    premiumMembership: "高级版订阅",
    freePlanUsing: "正在使用免费方案",
    usingPlan: " 方案使用中",
    changePlan: "更改方案",
    cancelSubscription: "取消自动续费",
    cancelSubConfirm: "确定取消自动续费吗？到期前您仍可继续使用高级功能。",
    subCancelledMsg: "已取消自动续费，高级权益保留至到期日。",
    scheduledCancelLabel: "已取消续费",
    nextPayDateLabel: "下次续费日: ",
    expDateLabel: "到期日: ",
    daysLeftLabel: "天后到期",
    deleteAccountBtn: "⚠️ 注销账号",
    deleteAccountConfirm: "确定要注销账号吗？\n\n⚠️ 警告：注销后订阅将被取消，剩余高级体验时间及所有数据将被永久删除。",
    deleteAccountSuccess: "账号已成功注销。",
    loginSub: "请登录以使用服务",
    signupSub: "创建新账号",
    signup: "注册",
    nicknameLabel: "姓名（昵称）",
    emailLabel: "电子邮箱",
    passwordLabel: "密码",
    confirmPasswordLabel: "确认密码",
    passwordCheckPrompt: "Please check password requirements.",
    passwordMismatch: "Passwords do not match.",
    emailVerificationAlert: "Email not verified. Please click the verification link sent to your inbox before logging in.",
    emailAlreadyInUse: "This email address is already registered.",
    loginBtn: "登录",
    signupBtn: "注册",
    or: "或",
    googleLogin: "使用 Google 继续",
    pricingSubNotice: "* 订阅后可随时在设置中管理或取消。",
    promptNewDeckName: "请输入新单词本名称:",
    deckNameMismatch: "单词本名称不一致。",
    loginRequired: "该服务需要登录。",
    subscribeConfirmPre: " 方案吗？",
    subscribeSuccessPost: " 高级版订阅成功！",
    imageOnlyAlert: "只能上传图片文件。",
    signupSuccess: "Sign up complete! Verification email sent. Please verify your email before logging in.",
    profileUpdateSuccess: "个人信息更新成功！",
    dailyLimitBadge: "今日免费剩余: ",
    dailyLimitReached: "您已使用完今日3次免费分析额度。升级高级版享受无限使用！",
    loginGateMsg: "请登录后使用句子分析功能。",
    quizLockedTitle: "🔒 单词测验为高级版专属功能",
    quizLockedDesc: "加入高级版，解锁无限测验与句子分析！",
    pdfLockedMsg: "生成PDF测试卷功能仅供高级版用户使用。"
  },
  'zh-TW': {
    analyzeTab: "句子分析",
    decksTab: "單字整理",
    quizTab: "單字測驗",
    streak: "天連續",
    membership: "高級版",
    login: "登入",
    logout: "登出",
    loginSignup: "登入 / 註冊",
    deckSidebarTitle: "單字整理",
    deckLabel: "卡片盒:",
    newDeck: "+ 新建單字本",
    searchPlaceholder: "🔍 搜尋單字/釋義...",
    inputTitle: "輸入日語句子或附加圖片",
    inputPlaceholder: "請輸入要分析的日語句子或文章，或拖放/Ctrl+V貼上圖片。",
    selectImage: "🖼️ 選擇圖片檔案",
    dragNotice: "支援 Ctrl+V 或拖放圖片",
    analyzeBtn: "開始分析",
    analyzing: "分析中...",
    cooldown: "請稍候...",
    noteTitle: "原文筆記",
    stopAudio: "停止",
    fontSerif: "明朝體",
    fontSans: "黑體",
    wordCardTitle: "核心詞彙",
    kanjiCardTitle: "重點漢字",
    grammarCardTitle: "文法結構",
    targetDeck: "儲存至單字本:",
    addWordBtn: "+ 儲存至單字整理",
    hideMeaning: "🙈 隱藏釋義",
    showMeaning: "🙈 顯示釋義",
    partOfSpeech: "詞性",
    meaning: "釋義",
    delete: "刪除",
    exportAnki: "⚡ 匯出 Anki 卡包",
    makePdf: "📝 生成測試卷 (PDF)",
    premiumTitle: "YomiYomi 高級版",
    premiumDesc: "享受無限句子分析、AI 單字整理同步及測驗功能。",
    plan3m: "3個月 方案",
    plan1y: "1年 方案",
    planLifetime: "終身卡",
    off20: "20% 優惠",
    bestTag: "🔥 BEST",
    price3m: "$12.00",
    price1y: "$38.40",
    priceLifetime: "$45.00",
    perMonth3: "$4.00/月",
    perMonth12: "$3.20/月",
    unlimitedText: "無限使用",
    selectPlan: "選擇",
    subscribePlan: "立即訂閱",
    payTitlePre: "請選擇 [",
    payTitlePost: " 方案] 的支付方式",
    payAmountLabel: "支付金額：",
    reselectPlan: "◀ 重新選擇方案",
    close: "✕",
    modeFurigana: "振假名(上)",
    modeYomigana: "讀音(旁)",
    modeOff: "關閉",
    gojuonChart: "五十音圖",
    hiragana: "平假名",
    katakana: "片假名",
    recSitesTitle: "推薦學習網站",
    noSavedWords: "暫無儲存的單字。",
    noSearchWords: "未找到匹配的單字。",
    savedWordsLabel: "已儲存單字: ",
    unitCount: "個",
    charCount: "字",
    unitTimes: "次",
    confirmBtn: "確定",
    cancelBtn: "取消",
    wordCardListTitle: "單字卡片列表",
    allDeckTitle: "全部單字本",
    quizTitle: "單字選擇題測驗",
    quizSelectDesc: "請選擇出題單字本。",
    quizStartBtn: "開始測驗",
    quizCompleteTitle: "測驗完成！",
    quizScoreText: "答對題目。",
    quizBackBtn: "返回單字本選擇",
    quizSurrenderBtn: "🏳️ 放棄測驗",
    quizMinCardsAlert: "需要至少 3 個儲存的單字才能開始測驗。",
    quizSurrenderConfirm: "確定要放棄當前測驗嗎？",
    logoutConfirm: "確定要退出登入嗎？",
    deckDeleteModalTitle: "確認刪除單字本",
    deckDeleteModalDesc: "確定刪除此單字本嗎？\n請在下方輸入單字本名稱以確認。",
    newDeckModalTitle: "新建單字本",
    newDeckModalPlaceholder: "請輸入單字本名稱",
    createBtn: "創建",
    duplicateWordMsg: "該單字已存在於單字本中。",
    alertNoDeck: "必須至少保留一個單字本。",
    settingsTitle: "個人資訊與設定",
    changeNickname: "修改暱稱",
    changeLanguage: "語言偏好設定",
    saveProfileBtn: "儲存個人資訊",
    premiumMembership: "高級版訂閱",
    freePlanUsing: "正在使用免費方案",
    usingPlan: " 方案使用中",
    changePlan: "更改方案",
    cancelSubscription: "取消自動續費",
    cancelSubConfirm: "確定取消自動續費嗎？到期前您仍可繼續使用高級功能。",
    subCancelledMsg: "已取消自動續費，高級權益保留至到期日。",
    scheduledCancelLabel: "已取消續費",
    nextPayDateLabel: "下次續費日: ",
    expDateLabel: "到期日: ",
    daysLeftLabel: "天後到期",
    deleteAccountBtn: "⚠️ 註銷帳號",
    deleteAccountConfirm: "確定要註銷帳號嗎？\n\n⚠️ 警告：註銷後訂閱將被取消，剩餘高級體驗時間及所有數據將被永久刪除。",
    deleteAccountSuccess: "帳號已成功註銷。",
    loginSub: "請登入以使用服務",
    signupSub: "創建新帳號",
    signup: "註冊",
    nicknameLabel: "姓名（暱稱）",
    emailLabel: "電子郵件",
    passwordLabel: "密碼",
    confirmPasswordLabel: "確認密碼",
    passwordCheckPrompt: "Please check password requirements.",
    passwordMismatch: "Passwords do not match.",
    emailVerificationAlert: "Email not verified. Please click the verification link sent to your inbox before logging in.",
    emailAlreadyInUse: "This email address is already registered.",
    loginBtn: "登入",
    signupBtn: "註冊",
    or: "或",
    googleLogin: "使用 Google 繼續",
    pricingSubNotice: "* 訂閱後可隨時在設定中管理或取消。",
    promptNewDeckName: "請輸入新單字本名稱:",
    deckNameMismatch: "單字本名稱不一致。",
    loginRequired: "該服務需要登入。",
    subscribeConfirmPre: " 方案嗎？",
    subscribeSuccessPost: " 高級版訂閱成功！",
    imageOnlyAlert: "只能上傳圖片檔案。",
    signupSuccess: "Sign up complete! Verification email sent. Please verify your email before logging in.",
    profileUpdateSuccess: "個人資訊更新成功！",
    dailyLimitBadge: "今日免費剩餘: ",
    dailyLimitReached: "您已使用完今日3次免費分析額度。升級高級版享受無限使用！",
    loginGateMsg: "請登入後使用句子分析功能。",
    quizLockedTitle: "🔒 單字測驗為高級版專屬功能",
    quizLockedDesc: "加入高級版，解鎖無限測驗與句子分析！",
    pdfLockedMsg: "生成PDF測試卷功能僅供高級版用戶使用。"
  },
  ja: {
    analyzeTab: "文章分析",
    decksTab: "単語帳管理",
    quizTab: "単語テスト",
    streak: "日連続",
    membership: "プレミアム",
    login: "ログイン",
    logout: "ログアウト",
    loginSignup: "ログイン / 会員登録",
    deckSidebarTitle: "単語帳",
    deckLabel: "デッキ:",
    newDeck: "+ 新規デッキ",
    searchPlaceholder: "🔍 単語・意味を検索...",
    inputTitle: "日本語の文章入力または画像添付",
    inputPlaceholder: "解析する日本語の文章や記事を入力するか、画像をドラッグ＆ドロップ/Ctrl+Vで貼り付けてください。",
    selectImage: "🖼️ 画像ファイルを選択",
    dragNotice: "Ctrl+V やドラッグ＆ドロップも可能",
    analyzeBtn: "解析する",
    analyzing: "解析中...",
    cooldown: "お待ちください...",
    noteTitle: "本文ノート",
    stopAudio: "停止",
    fontSerif: "明朝体",
    fontSans: "ゴシック体",
    wordCardTitle: "重要単語カード",
    kanjiCardTitle: "重要漢字情報",
    grammarCardTitle: "重要文法情報",
    targetDeck: "保存先単語帳:",
    addWordBtn: "+ 単語帳に保存",
    hideMeaning: "🙈 意味を隠す",
    showMeaning: "🙈 意味を表示",
    partOfSpeech: "品詞",
    meaning: "意味",
    delete: "削除",
    exportAnki: "⚡ Ankiデッキ出力",
    makePdf: "📝 テスト用紙作成 (PDF)",
    premiumTitle: "YomiYomi プレミアム",
    premiumDesc: "無制限の文章解析、AI単語帳同期およびクイズ機能をご利用いただけます。",
    plan3m: "3ヶ月プラン",
    plan1y: "1年間プラン",
    planLifetime: "買い切りプラン",
    off20: "20% OFF",
    bestTag: "🔥 BEST",
    price3m: "$12.00",
    price1y: "$38.40",
    priceLifetime: "$45.00",
    perMonth3: "$4.00/月",
    perMonth12: "$3.20/月",
    unlimitedText: "無制限",
    selectPlan: "選択する",
    subscribePlan: "登録する",
    payTitlePre: "[",
    payTitlePost: " プラン] 決済方法を選択してください",
    payAmountLabel: "決済金額：",
    reselectPlan: "◀ プランを再選択する",
    close: "✕",
    modeFurigana: "ふりがな",
    modeYomigana: "よみがな",
    modeOff: "OFF",
    gojuonChart: "五十音図",
    hiragana: "ひらがな",
    katakana: "カタカナ",
    recSitesTitle: "おすすめ学習サイト",
    noSavedWords: "保存された単語がありません。",
    noSearchWords: "検索結果がありません。",
    savedWordsLabel: "保存された単語: ",
    unitCount: "個",
    charCount: "文字",
    unitTimes: "回",
    confirmBtn: "確認",
    cancelBtn: "キャンセル",
    wordCardListTitle: "単語カードリスト",
    allDeckTitle: "全単語帳一覧",
    quizTitle: "単語暗記クイズ",
    quizSelectDesc: "出題する単語帳を選択してください。",
    quizStartBtn: "クイズを開始する",
    quizCompleteTitle: "クイズ完了！",
    quizScoreText: "正答しました。",
    quizBackBtn: "単語帳選択に戻る",
    quizSurrenderBtn: "🏳️ ギブアップ",
    quizMinCardsAlert: "クイズを開始するには少なくとも3語の保存が必要です。",
    quizSurrenderConfirm: "クイズを中断して選択画面に戻りますか？",
    logoutConfirm: "ログアウトしますか？",
    deckDeleteModalTitle: "単語帳削除の確認",
    deckDeleteModalDesc: "この単語帳を削除しますか？\n確認のため下に単語帳の名前を入力してください。",
    newDeckModalTitle: "新規単語帳作成",
    newDeckModalPlaceholder: "単語帳の名前を入力してください",
    createBtn: "作成",
    duplicateWordMsg: "すでに単語帳に存在する単語です。",
    alertNoDeck: "少なくとも1つの単語帳を保持する必要があります。",
    settingsTitle: "個人情報・設定",
    changeNickname: "ニックネーム変更",
    changeLanguage: "言語設定",
    saveProfileBtn: "プロフィール情報を保存",
    premiumMembership: "プレミアム登録",
    freePlanUsing: "無料プラン利用中",
    usingPlan: " プラン利用中",
    changePlan: "プラン変更",
    cancelSubscription: "解約予約",
    cancelSubConfirm: "自動更新を解約しますか？期限までは引き続きプレミアム機能をご利用いただけます。",
    subCancelledMsg: "解約が予約されました。有効期限までご利用いただけます。",
    scheduledCancelLabel: "解約予約中",
    nextPayDateLabel: "次回更新日: ",
    expDateLabel: "有効期限: ",
    daysLeftLabel: "日残り",
    deleteAccountBtn: "⚠️ アカウント退会",
    deleteAccountConfirm: "本当に退会しますか？\n\n⚠️ 注意: 退会すると自動決済がキャンセルされ、残りのプレミアム期間および全データが即座に消去されます。",
    deleteAccountSuccess: "アカウントが正常に退会されました。",
    loginSub: "サービス利用のためにログインしてください",
    signupSub: "新しいアカウントを作成",
    signup: "会員登録",
    nicknameLabel: "名前（ニックネーム）",
    emailLabel: "メールアドレス",
    passwordLabel: "パスワード",
    confirmPasswordLabel: "確認パスワード",
    passwordCheckPrompt: "Please check password requirements.",
    passwordMismatch: "Passwords do not match.",
    emailVerificationAlert: "Email not verified. Please click the verification link sent to your inbox before logging in.",
    emailAlreadyInUse: "This email address is already registered.",
    loginBtn: "ログイン",
    signupBtn: "登録",
    or: "または",
    googleLogin: "Googleで続ける",
    pricingSubNotice: "* 登録後、いつでも設定からサブスクリプションを管理・解約できます。",
    promptNewDeckName: "新しい単語帳の名前を入力してください:",
    deckNameMismatch: "単語帳の名前が一致しません。",
    loginRequired: "ログインが必要なサービスです。",
    subscribeConfirmPre: " プランに登録しますか？",
    subscribeSuccessPost: " プレミアム登録が完了しました！",
    imageOnlyAlert: "画像ファイルのみアップロードできます。",
    signupSuccess: "Sign up complete! Verification email sent. Please verify your email before logging in.",
    profileUpdateSuccess: "プロフィール情報を更新しました！",
    dailyLimitBadge: "本日の無料残数: ",
    dailyLimitReached: "本日の無料解析上限（3回）に達しました。プレミアムプランで無制限にご利用いただけます！",
    loginGateMsg: "文章解析機能のご利用にはログインが必要です。",
    quizLockedTitle: "🔒 単語テストはプレミアム限定機能です",
    quizLockedDesc: "プレミアムに登録して、無制限の単語テストと文章解析を活用しましょう！",
    pdfLockedMsg: "PDFテスト用紙作成機能はプレミアム会員限定サービスです。"
  }
};

export const RECOMMENDED_SITES: Record<Lang, Array<{ name: string; url: string; desc: string; icon: string }>> = {
  ko: [
    { name: 'NHK News Web', url: 'https://www3.nhk.or.jp/news/', desc: '실제 일본 현지 뉴스를 실시간으로 읽고 yomiyomi로 복사해 문장을 해독해 보세요.', icon: '📰' },
    { name: 'JLPT Sensei', url: 'https://jlptsensei.com/', desc: 'JLPT 급수별 어휘, 문법 구조, 예문을 체계적으로 찾아보는 학습 사이트', icon: '📚' },
    { name: 'Tofugu', url: 'https://www.tofugu.com/', desc: '일본어 뉘앙스 차이, 암기 팁, 문화 콘텐츠를 다루는 종합 가이드 사이트', icon: '🐡' }
  ],
  en: [
    { name: 'NHK News Web', url: 'https://www3.nhk.or.jp/news/', desc: 'Read authentic Japanese news in real-time and analyze text seamlessly with yomiyomi.', icon: '📰' },
    { name: 'JLPT Sensei', url: 'https://jlptsensei.com/', desc: 'Study site for JLPT vocabulary, grammar, and example sentences.', icon: '📚' },
    { name: 'Tofugu', url: 'https://www.tofugu.com/', desc: 'Comprehensive guide covering Japanese nuances, mnemonics, and culture.', icon: '🐡' }
  ],
  'zh-CN': [
    { name: 'NHK News Web', url: 'https://www3.nhk.or.jp/news/', desc: '实时阅读日本地道新闻，可配合 yomiyomi 复制解析句子。', icon: '📰' },
    { name: 'JLPT Sensei', url: 'https://jlptsensei.com/', desc: '按JLPT级别分类整理词汇、语法及例句的学习网站。', icon: '📚' },
    { name: 'Tofugu', url: 'https://www.tofugu.com/', desc: '涵盖日语细微差别、记忆技巧和文化内容的综合指南。', icon: '🐡' }
  ],
  'zh-TW': [
    { name: 'NHK News Web', url: 'https://www3.nhk.or.jp/news/', desc: '實時閱讀日本地道新聞，可配合 yomiyomi 複製解析句子。', icon: '📰' },
    { name: 'JLPT Sensei', url: 'https://jlptsensei.com/', desc: '按JLPT級別分類整理詞彙、語法及例句的學習網站。', icon: '📚' },
    { name: 'Tofugu', url: 'https://www.tofugu.com/', desc: '涵蓋日語細微差別、記憶技巧和文化內容的綜合指南。', icon: '🐡' }
  ],
  ja: [
    { name: 'NHK News Web', url: 'https://www3.nhk.or.jp/news/', desc: 'リアルタイムのニュース記事を読み、yomiyomiに貼り付けて文章を解析してみましょう。', icon: '📰' },
    { name: 'JLPT Sensei', url: 'https://jlptsensei.com/', desc: 'JLPT級別の語彙、文法構造、例文を体系的に探せる学習サイト。', icon: '📚' },
    { name: 'Tofugu', url: 'https://www.tofugu.com/', desc: '日本語のニュアンスの違い、暗記のコツ、文化コンテンツを扱う総合ガイド。', icon: '🐡' }
  ]
};