[{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useState'.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 10,
	"endLineNumber": 1,
	"endColumn": 18,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useEffect'.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 20,
	"endLineNumber": 1,
	"endColumn": 29,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'createPortal'.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 10,
	"endLineNumber": 2,
	"endColumn": 22,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'signInWithEmailAndPassword'.",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 3,
	"endLineNumber": 4,
	"endColumn": 29,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'createUserWithEmailAndPassword'.",
	"source": "ts",
	"startLineNumber": 5,
	"startColumn": 3,
	"endLineNumber": 5,
	"endColumn": 33,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'signInWithPopup'.",
	"source": "ts",
	"startLineNumber": 6,
	"startColumn": 3,
	"endLineNumber": 6,
	"endColumn": 18,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'signOut'.",
	"source": "ts",
	"startLineNumber": 7,
	"startColumn": 3,
	"endLineNumber": 7,
	"endColumn": 10,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'onAuthStateChanged'.",
	"source": "ts",
	"startLineNumber": 8,
	"startColumn": 3,
	"endLineNumber": 8,
	"endColumn": 21,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'updateProfile'.",
	"source": "ts",
	"startLineNumber": 9,
	"startColumn": 3,
	"endLineNumber": 9,
	"endColumn": 16,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'sendEmailVerification'.",
	"source": "ts",
	"startLineNumber": 10,
	"startColumn": 3,
	"endLineNumber": 10,
	"endColumn": 24,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'deleteUser'.",
	"source": "ts",
	"startLineNumber": 11,
	"startColumn": 3,
	"endLineNumber": 11,
	"endColumn": 13,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'doc'.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 10,
	"endLineNumber": 13,
	"endColumn": 13,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'setDoc'.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 15,
	"endLineNumber": 13,
	"endColumn": 21,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'onSnapshot'.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 23,
	"endLineNumber": 13,
	"endColumn": 33,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'deleteDoc'.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 35,
	"endLineNumber": 13,
	"endColumn": 44,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'auth'.",
	"source": "ts",
	"startLineNumber": 14,
	"startColumn": 10,
	"endLineNumber": 14,
	"endColumn": 14,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'googleProvider'.",
	"source": "ts",
	"startLineNumber": 14,
	"startColumn": 16,
	"endLineNumber": 14,
	"endColumn": 30,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'db'.",
	"source": "ts",
	"startLineNumber": 14,
	"startColumn": 32,
	"endLineNumber": 14,
	"endColumn": 34,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'Lang'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 15,
	"endLineNumber": 16,
	"endColumn": 19,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'KanjiInfo'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 21,
	"endLineNumber": 16,
	"endColumn": 30,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'WordInfo'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 32,
	"endLineNumber": 16,
	"endColumn": 40,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'GrammarInfo'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 42,
	"endLineNumber": 16,
	"endColumn": 53,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'AnalysisResult'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 55,
	"endLineNumber": 16,
	"endColumn": 69,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'Deck'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 71,
	"endLineNumber": 16,
	"endColumn": 75,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'UserProfile'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 77,
	"endLineNumber": 16,
	"endColumn": 88,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'PORTONE_STORE_ID'.",
	"source": "ts",
	"startLineNumber": 18,
	"startColumn": 3,
	"endLineNumber": 18,
	"endColumn": 19,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'CHANNEL_KEY_KAKAOPAY'.",
	"source": "ts",
	"startLineNumber": 19,
	"startColumn": 3,
	"endLineNumber": 19,
	"endColumn": 23,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'CHANNEL_KEY_EXIMBAY'.",
	"source": "ts",
	"startLineNumber": 20,
	"startColumn": 3,
	"endLineNumber": 20,
	"endColumn": 22,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'MAX_TEXT_LENGTH'.",
	"source": "ts",
	"startLineNumber": 21,
	"startColumn": 3,
	"endLineNumber": 21,
	"endColumn": 18,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'HIRAGANA_GRID'.",
	"source": "ts",
	"startLineNumber": 22,
	"startColumn": 3,
	"endLineNumber": 22,
	"endColumn": 16,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'KATAKANA_GRID'.",
	"source": "ts",
	"startLineNumber": 23,
	"startColumn": 3,
	"endLineNumber": 23,
	"endColumn": 16,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'DICT'.",
	"source": "ts",
	"startLineNumber": 24,
	"startColumn": 3,
	"endLineNumber": 24,
	"endColumn": 7,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'RECOMMENDED_SITES'.",
	"source": "ts",
	"startLineNumber": 25,
	"startColumn": 3,
	"endLineNumber": 25,
	"endColumn": 20,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'getLocalizedPOS'.",
	"source": "ts",
	"startLineNumber": 28,
	"startColumn": 3,
	"endLineNumber": 28,
	"endColumn": 18,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'getLocalizedText'.",
	"source": "ts",
	"startLineNumber": 29,
	"startColumn": 3,
	"endLineNumber": 29,
	"endColumn": 19,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'calculateDaysLeft'.",
	"source": "ts",
	"startLineNumber": 30,
	"startColumn": 3,
	"endLineNumber": 30,
	"endColumn": 20,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'sanitizeDecks'.",
	"source": "ts",
	"startLineNumber": 31,
	"startColumn": 3,
	"endLineNumber": 31,
	"endColumn": 16,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'parseRubySentence'.",
	"source": "ts",
	"startLineNumber": 32,
	"startColumn": 3,
	"endLineNumber": 32,
	"endColumn": 20,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'analyzeJapanese'.",
	"source": "ts",
	"startLineNumber": 33,
	"startColumn": 3,
	"endLineNumber": 33,
	"endColumn": 18,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'convertUsdToKrw'.",
	"source": "ts",
	"startLineNumber": 34,
	"startColumn": 3,
	"endLineNumber": 34,
	"endColumn": 18,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'CardCarousel'.",
	"source": "ts",
	"startLineNumber": 36,
	"startColumn": 10,
	"endLineNumber": 36,
	"endColumn": 22,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'SidebarWordCarousel'.",
	"source": "ts",
	"startLineNumber": 37,
	"startColumn": 10,
	"endLineNumber": 37,
	"endColumn": 29,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'LegalModal'.",
	"source": "ts",
	"startLineNumber": 38,
	"startColumn": 10,
	"endLineNumber": 38,
	"endColumn": 20,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'getLegalDocument'.",
	"source": "ts",
	"startLineNumber": 39,
	"startColumn": 10,
	"endLineNumber": 39,
	"endColumn": 26,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'LegalDocType'.",
	"source": "ts",
	"startLineNumber": 40,
	"startColumn": 15,
	"endLineNumber": 40,
	"endColumn": 27,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'LegalDocument'.",
	"source": "ts",
	"startLineNumber": 40,
	"startColumn": 29,
	"endLineNumber": 40,
	"endColumn": 42,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useUserStore'.",
	"source": "ts",
	"startLineNumber": 42,
	"startColumn": 10,
	"endLineNumber": 42,
	"endColumn": 22,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useDeckStore'.",
	"source": "ts",
	"startLineNumber": 43,
	"startColumn": 10,
	"endLineNumber": 43,
	"endColumn": 22,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useUIStore'.",
	"source": "ts",
	"startLineNumber": 44,
	"startColumn": 10,
	"endLineNumber": 44,
	"endColumn": 20,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2451",
	"severity": 8,
	"message": "Cannot redeclare block-scoped variable 'DEFAULT_DECK_DATA'.",
	"source": "ts",
	"startLineNumber": 52,
	"startColumn": 7,
	"endLineNumber": 52,
	"endColumn": 24,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2323",
	"severity": 8,
	"message": "Cannot redeclare exported variable 'default'.",
	"source": "ts",
	"startLineNumber": 59,
	"startColumn": 25,
	"endLineNumber": 59,
	"endColumn": 28,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 59,
	"startColumn": 25,
	"endLineNumber": 59,
	"endColumn": 28,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useState'.",
	"source": "ts",
	"startLineNumber": 2648,
	"startColumn": 11,
	"endLineNumber": 2648,
	"endColumn": 19,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useEffect'.",
	"source": "ts",
	"startLineNumber": 2648,
	"startColumn": 21,
	"endLineNumber": 2648,
	"endColumn": 30,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'createPortal'.",
	"source": "ts",
	"startLineNumber": 2649,
	"startColumn": 10,
	"endLineNumber": 2649,
	"endColumn": 22,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'signInWithEmailAndPassword'.",
	"source": "ts",
	"startLineNumber": 2651,
	"startColumn": 3,
	"endLineNumber": 2651,
	"endColumn": 29,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'createUserWithEmailAndPassword'.",
	"source": "ts",
	"startLineNumber": 2652,
	"startColumn": 3,
	"endLineNumber": 2652,
	"endColumn": 33,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'signInWithPopup'.",
	"source": "ts",
	"startLineNumber": 2653,
	"startColumn": 3,
	"endLineNumber": 2653,
	"endColumn": 18,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'signOut'.",
	"source": "ts",
	"startLineNumber": 2654,
	"startColumn": 3,
	"endLineNumber": 2654,
	"endColumn": 10,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'onAuthStateChanged'.",
	"source": "ts",
	"startLineNumber": 2655,
	"startColumn": 3,
	"endLineNumber": 2655,
	"endColumn": 21,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'updateProfile'.",
	"source": "ts",
	"startLineNumber": 2656,
	"startColumn": 3,
	"endLineNumber": 2656,
	"endColumn": 16,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'sendEmailVerification'.",
	"source": "ts",
	"startLineNumber": 2657,
	"startColumn": 3,
	"endLineNumber": 2657,
	"endColumn": 24,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'deleteUser'.",
	"source": "ts",
	"startLineNumber": 2658,
	"startColumn": 3,
	"endLineNumber": 2658,
	"endColumn": 13,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'doc'.",
	"source": "ts",
	"startLineNumber": 2660,
	"startColumn": 10,
	"endLineNumber": 2660,
	"endColumn": 13,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'setDoc'.",
	"source": "ts",
	"startLineNumber": 2660,
	"startColumn": 15,
	"endLineNumber": 2660,
	"endColumn": 21,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'onSnapshot'.",
	"source": "ts",
	"startLineNumber": 2660,
	"startColumn": 23,
	"endLineNumber": 2660,
	"endColumn": 33,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'deleteDoc'.",
	"source": "ts",
	"startLineNumber": 2660,
	"startColumn": 35,
	"endLineNumber": 2660,
	"endColumn": 44,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "7016",
	"severity": 8,
	"message": "Could not find a declaration file for module 'anki-apkg-export'. 'c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/node_modules/anki-apkg-export/dist/index.js' implicitly has an 'any' type.\n  Try `npm i --save-dev @types/anki-apkg-export` if it exists or add a new declaration (.d.ts) file containing `declare module 'anki-apkg-export';`",
	"source": "ts",
	"startLineNumber": 2661,
	"startColumn": 24,
	"endLineNumber": 2661,
	"endColumn": 42,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'auth'.",
	"source": "ts",
	"startLineNumber": 2662,
	"startColumn": 10,
	"endLineNumber": 2662,
	"endColumn": 14,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'googleProvider'.",
	"source": "ts",
	"startLineNumber": 2662,
	"startColumn": 16,
	"endLineNumber": 2662,
	"endColumn": 30,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'db'.",
	"source": "ts",
	"startLineNumber": 2662,
	"startColumn": 32,
	"endLineNumber": 2662,
	"endColumn": 34,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'Lang'.",
	"source": "ts",
	"startLineNumber": 2664,
	"startColumn": 15,
	"endLineNumber": 2664,
	"endColumn": 19,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'KanjiInfo'.",
	"source": "ts",
	"startLineNumber": 2664,
	"startColumn": 21,
	"endLineNumber": 2664,
	"endColumn": 30,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'WordInfo'.",
	"source": "ts",
	"startLineNumber": 2664,
	"startColumn": 32,
	"endLineNumber": 2664,
	"endColumn": 40,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'GrammarInfo'.",
	"source": "ts",
	"startLineNumber": 2664,
	"startColumn": 42,
	"endLineNumber": 2664,
	"endColumn": 53,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'AnalysisResult'.",
	"source": "ts",
	"startLineNumber": 2664,
	"startColumn": 55,
	"endLineNumber": 2664,
	"endColumn": 69,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'Deck'.",
	"source": "ts",
	"startLineNumber": 2664,
	"startColumn": 71,
	"endLineNumber": 2664,
	"endColumn": 75,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'UserProfile'.",
	"source": "ts",
	"startLineNumber": 2664,
	"startColumn": 77,
	"endLineNumber": 2664,
	"endColumn": 88,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'PORTONE_STORE_ID'.",
	"source": "ts",
	"startLineNumber": 2666,
	"startColumn": 3,
	"endLineNumber": 2666,
	"endColumn": 19,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'CHANNEL_KEY_KAKAOPAY'.",
	"source": "ts",
	"startLineNumber": 2667,
	"startColumn": 3,
	"endLineNumber": 2667,
	"endColumn": 23,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'CHANNEL_KEY_EXIMBAY'.",
	"source": "ts",
	"startLineNumber": 2668,
	"startColumn": 3,
	"endLineNumber": 2668,
	"endColumn": 22,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'MAX_TEXT_LENGTH'.",
	"source": "ts",
	"startLineNumber": 2669,
	"startColumn": 3,
	"endLineNumber": 2669,
	"endColumn": 18,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'HIRAGANA_GRID'.",
	"source": "ts",
	"startLineNumber": 2670,
	"startColumn": 3,
	"endLineNumber": 2670,
	"endColumn": 16,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'KATAKANA_GRID'.",
	"source": "ts",
	"startLineNumber": 2671,
	"startColumn": 3,
	"endLineNumber": 2671,
	"endColumn": 16,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'DICT'.",
	"source": "ts",
	"startLineNumber": 2672,
	"startColumn": 3,
	"endLineNumber": 2672,
	"endColumn": 7,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'RECOMMENDED_SITES'.",
	"source": "ts",
	"startLineNumber": 2673,
	"startColumn": 3,
	"endLineNumber": 2673,
	"endColumn": 20,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'getLocalizedPOS'.",
	"source": "ts",
	"startLineNumber": 2676,
	"startColumn": 3,
	"endLineNumber": 2676,
	"endColumn": 18,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'getLocalizedText'.",
	"source": "ts",
	"startLineNumber": 2677,
	"startColumn": 3,
	"endLineNumber": 2677,
	"endColumn": 19,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'calculateDaysLeft'.",
	"source": "ts",
	"startLineNumber": 2678,
	"startColumn": 3,
	"endLineNumber": 2678,
	"endColumn": 20,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'sanitizeDecks'.",
	"source": "ts",
	"startLineNumber": 2679,
	"startColumn": 3,
	"endLineNumber": 2679,
	"endColumn": 16,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'parseRubySentence'.",
	"source": "ts",
	"startLineNumber": 2680,
	"startColumn": 3,
	"endLineNumber": 2680,
	"endColumn": 20,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'analyzeJapanese'.",
	"source": "ts",
	"startLineNumber": 2681,
	"startColumn": 3,
	"endLineNumber": 2681,
	"endColumn": 18,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'convertUsdToKrw'.",
	"source": "ts",
	"startLineNumber": 2682,
	"startColumn": 3,
	"endLineNumber": 2682,
	"endColumn": 18,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'CardCarousel'.",
	"source": "ts",
	"startLineNumber": 2684,
	"startColumn": 10,
	"endLineNumber": 2684,
	"endColumn": 22,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'SidebarWordCarousel'.",
	"source": "ts",
	"startLineNumber": 2685,
	"startColumn": 10,
	"endLineNumber": 2685,
	"endColumn": 29,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'LegalModal'.",
	"source": "ts",
	"startLineNumber": 2686,
	"startColumn": 10,
	"endLineNumber": 2686,
	"endColumn": 20,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'getLegalDocument'.",
	"source": "ts",
	"startLineNumber": 2687,
	"startColumn": 10,
	"endLineNumber": 2687,
	"endColumn": 26,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'LegalDocType'.",
	"source": "ts",
	"startLineNumber": 2688,
	"startColumn": 15,
	"endLineNumber": 2688,
	"endColumn": 27,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'LegalDocument'.",
	"source": "ts",
	"startLineNumber": 2688,
	"startColumn": 29,
	"endLineNumber": 2688,
	"endColumn": 42,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useUserStore'.",
	"source": "ts",
	"startLineNumber": 2690,
	"startColumn": 10,
	"endLineNumber": 2690,
	"endColumn": 22,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useDeckStore'.",
	"source": "ts",
	"startLineNumber": 2691,
	"startColumn": 10,
	"endLineNumber": 2691,
	"endColumn": 22,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2300",
	"severity": 8,
	"message": "Duplicate identifier 'useUIStore'.",
	"source": "ts",
	"startLineNumber": 2692,
	"startColumn": 10,
	"endLineNumber": 2692,
	"endColumn": 20,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2451",
	"severity": 8,
	"message": "Cannot redeclare block-scoped variable 'DEFAULT_DECK_DATA'.",
	"source": "ts",
	"startLineNumber": 2700,
	"startColumn": 7,
	"endLineNumber": 2700,
	"endColumn": 24,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2323",
	"severity": 8,
	"message": "Cannot redeclare exported variable 'default'.",
	"source": "ts",
	"startLineNumber": 2707,
	"startColumn": 25,
	"endLineNumber": 2707,
	"endColumn": 28,
	"modelVersionId": 8,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/wonhy/OneDrive/바탕 화면/Project/YomiYomi/src/App.tsx",
	"owner": "typescript",
	"code": "2393",
	"severity": 8,
	"message": "Duplicate function implementation.",
	"source": "ts",
	"startLineNumber": 2707,
	"startColumn": 25,
	"endLineNumber": 2707,
	"endColumn": 28,
	"modelVersionId": 8,
	"origin": "extHost1"
}]